---
- hosts: colo_machine
  gather_facts: no

  tasks:
    - name: edit .bash_aliases
      when: inventory_hostname in groups['colo_machine']
      ansible.builtin.blockinfile:
        path: /home/zanskar/.bash_aliases
        create: yes
        owner: zanskar
        # append_newline: true
        # prepend_newline: true
        block: |
          alias list-algo='ps -ea | grep algo'
          alias list-dc='ps -ea | grep drop_copy'
          alias list-publisher='ps -ea | grep publisher'
          alias show-rtt-logs='bash /home/zanskar/ready_to_trade/ready_to_trade.sh'
      tags:
        - bashrc_files
        - post_installation

    - name: edit .bash_functions
      when: inventory_hostname in groups['colo_machine']
      ansible.builtin.blockinfile:
        path: /home/zanskar/.bash_functions
        create: yes
        owner: zanskar
        # append_newline: true
        # prepend_newline: true
        block: |
          show-logs () {
          date_str=$(date +"%Y%m%d")
          log_file=/home/zanskar/logs/algo/$1_${date_str}.log
          less +F ${log_file}
          }

          show-lh () {
              date_str=$(date +"%Y%m%d")
                  if [[ $# -gt 0 ]]; then
                          log_file=logs/apps/linehandler_$1_${date_str}.log
                  else
                          log_file=logs/apps/linehandler_${date_str}.log
                  fi
              less +F ${log_file}
          }

          function watchcsv(){
            reload=5
            if [[ $# -gt 1 ]]; then
                reload=$2
            fi

            watch -n $reload -d "head -n 10000000 $1 | column -t -s ",""
          }

          function showcsv(){
            prod_box="08"
            file_type=$1
            strat=$2
            index=${strat:0:2}
            num=${strat:2:1}
            indexname=""
            if [ "$index" == "bn" ]; then
                indexname="BankNifty"
            elif [ "$index" == "nf" ]; then
                indexname="Nifty"
            fi

            date_str=$(date +"%Y%m%d")

            if [ "$file_type" == "health" ]; then
                watchcsv /home/zanskar/titan_data/$indexname/health/Monitor_PROD_ZR${prod_box}_0${num}_${date_str}.csv
            fi
          }

          function show-health(){
            showcsv health $1
          }

          function list-lh(){
              ps aux | grep linehandler | grep /bin/linehandler | cut -d' ' -f 15
          }

          function list-pub(){
              ps aux | grep publisher | grep /bin/*publisher | cut -d' ' -f 15
          }

          function lesscsv(){
              head -n 10000000 $1 | column -t -s "," | less
          }

          function greplesscsv(){
              head -n 10000000 $2 | grep $1 | column -t -s "," | less
          }

          function diffcsv(){
              vimdiff <(lesscsv $1) <(lesscsv $2)
          }

          function grepdiffcsv(){
              vimdiff <(greplesscsv $1 $2) <(greplesscsv $1 $3)
          }
      tags:
        - bashrc_files
        - post_installation


    - name: edit .bashrc
      when: inventory_hostname in groups['colo_machine']
      ansible.builtin.blockinfile:
        path: /home/zanskar/.bashrc
        block: |
          if [ -f ~/.bash_functions ]; then
              . ~/.bash_functions
          fi

          if [ -f /home/zanskar/ready_to_trade/ready_to_trade.sh ]; then
                  if [ -z "$(bash /home/zanskar/ready_to_trade/ready_to_trade.sh | grep ERR)" ]; then
                          printf "\n\033[1;32mReady to Trade! \n\n"
                  else
                          echo ""
                          bash /home/zanskar/ready_to_trade/ready_to_trade.sh | grep ERR
                          echo ""
                          printf "%-20s Run \033[1;31mshow-rtt-logs \033[0mto see the whole ready_to_trade log!\n\n"
                  fi
          else
                  echo "RTT Script is not deployed on this device!"
          fi
      tags:
        - bashrc_files
        - post_installation
